### ISSUE TITLE
Copying a <script> erases it

### ISSUE THREAD

**Issue by oagix** [leodr/paste-html-as-jsx#11]
Trying to copy a script from an .HTML file, like:

```
<script>
      window.Example_Config = window.Example_Config || [];
      window.Example_Config.push({ key: "XXXXXXXX" });
</script>
<script async="" src="https://widget.example.co/v2/widget.js"></script>
```

...to a Next.js `_document.js` file, causes it to be erased completely on paste.

**Comment by leodr** [comment]
I'm not currently working on the project anymore, since I don't have any use case for it anymore.

So I unfortunately won't work on this bug, however feel free to fork and if you want to submit a PR I'll be happy to review it and do a release.

**Comment by leodr** [comment]
Works now with the release of [v1.0.0](https://github.com/leodr/paste-html-as-jsx/releases/tag/v1.0.0), now outputs the following JSX:

```jsx
<><script>{`
      window.Example_Config = window.Example_Config || [];
      window.Example_Config.push({ key: "XXXXXXXX" });
`}</script>
<script async src="https://widget.example.co/v2/widget.js" /></>
```
