### ISSUE TITLE
Some words get "converted" and cause jsx to become invalid

### ISSUE THREAD

**Issue by stingray21** [leodr/paste-html-as-jsx#12]
I noticed that some words get "converted" (e.g `health` becomes `healt=""h` and `saltstick` becomes `salt=""stick`) which then cause the resulting jsx to be invalid.
In most cases it's very obvious and easy to manually fix. But in large sections of html it's sometimes hard to find the error.

**Comment by leodr** [comment]
Could you give me a full example of HTML code that is wrongly converted? I'm currently working on a new conversion library and would like to add your case as a test case.

**Comment by leodr** [comment]
[v1.0.0](https://github.com/leodr/paste-html-as-jsx/releases/tag/v1.0.0) uses a new library to convert HTML into JSX. This issue should not happen anymore.

Please open another issue if this still happens for you.
