### ISSUE TITLE
Pasting a `Head` tag replaced with a `div`

### ISSUE THREAD

**Issue by pdevito3** [leodr/paste-html-as-jsx#3]
pasting in something like the below
```jsx
      <Head>
        <meta
          key="twitter:title"
          name="twitter:title"
          content="Tailwind CSS - Rapidly build modern websites without ever leaving your HTML."
        />
        <meta
          key="og:title"
          property="og:title"
          content="Tailwind CSS - Rapidly build modern websites without ever leaving your HTML."
        />
        <title>Tailwind CSS - Rapidly build modern websites without ever leaving your HTML.</title>
      </Head>
```

replaces `Head` with `div` like so:
```jsx
      <div>
  <meta key="twitter:title" name="twitter:title" content="Tailwind CSS - Rapidly build modern websites without ever leaving your HTML." />
  <meta key="og:title" property="og:title" content="Tailwind CSS - Rapidly build modern websites without ever leaving your HTML." />
  <title>Tailwind CSS - Rapidly build modern websites without ever leaving your HTML.</title>
</div>
```

**Comment by leodr** [comment]
Thanks for opening the issues, however I would not really consider this a bug, since `<Head>` is not a valid HTML tag.

The [`htmltojsx`](https://www.npmjs.com/package/htmltojsx)-package that we use under the hood probably replaces invalid tags with `<div>`.

**Comment by pdevito3** [comment]
gotcha. not the end of the world, but assumed it would keep it, especially in this case as it is a valid nextjs tag :-) even if it wasn't, would still personally want it to keep custom component tags like that. maybe you add a setting where we can control that? regardless, cool tool so far!

**Comment by leodr** [comment]
Oh so you are just copying JSX, not HTML now I get it. The extension currently doesn't detect if you are copying JSX and will just try to convert it to JSX again, which is why the tag gets messed up.

I'll see if I can make it so the extension detects that you copied JSX and not do any conversion then.

**Comment by leodr** [comment]
I added the detection of JSX tags for version 0.2.2, so the problem should be fixed when you upgrade.
