### ISSUE TITLE
format on demand vs auto formatting

### ISSUE THREAD

**Issue by JeffBeltran** [leodr/paste-html-as-jsx#9]
Thanks for creating this handy plugin, quick question. Can you add the ability to ignore the pasting and instead allow us to "format as JSX" instead. 

this would be helpful when i have to switch between projects that use JSX and ones that don't. Right now i could just enable the package on a per project basis but like the idea of just having this as a setting/shortcut

Thanks,
Jeff

**Comment by leodr** [comment]
Yeah I thought about this, what do you think about a quick toggle in the bottom status bar?

I could implement that pretty easily.

**Comment by JeffBeltran** [comment]
that would be better than having to do it on per project, so yeah. ideally it would be cool to just highlight what you want and then open command palette and just type jsx or something like that. However, I would imagine the LOE would be much more than a simple button, so i say whatever is easiest for you.

**Comment by leodr** [comment]
What do you think about adding a setting that toggles the "mode" you are in:

- `automatic` mode automatically detects HTML in your clipboard and converts it to HTML
- `on-demand` mode does not do any detection and only converts your clipboard when you execute an action from the command palette

**Comment by leodr** [comment]
I added the option for `on-demand` mode in [version 0.3.0](https://github.com/leodr/paste-html-as-jsx/releases/tag/v0.3.0).

If you think a command that would turn selected HTML to JSX is still needed, please open another issue. I thought about it and currently don't see a use case where the conversion of selected text would be more ergonomic than clipboard conversion.

And thanks for the feedback btw!

**Comment by JeffBeltran** [comment]
agreed, i think this should do the trick. Thanks again and if i have more feedback i'll let you know. Cheers!
